bot2hook_rabbitmq:
  image: rabbitmq:3.6
  container_name: bot2hook_rabbitmq
  hostname: bot2hook_rabbitmq
  volumes:
    - ../storage/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@bot2hook_rabbitmq

bot2hook_lasp:
  build: ./bot2hook_lasp
  container_name: bot2hook_lasp
  links:
    - bot2hook_rabbitmq
  volumes:
    - ../:/http
    - ./bot2hook_lasp/supervisor:/supervisor
  environment:
    CONF_FILE: prod
