bot2hook_lasp:
  volumes:
    - ../sample/apache2:/apache2
    - ../sample/config:/http/app/config/env
    - ../sample/public:/http/public/sample
  links:
    - bot2hook_rabbitmq
  ports:
    - "80"
  environment:
    CONF_FILE: testing_webhook
  extra_hosts:
     - "bot2hook.local:172.17.0.1"
